name: GalaxyMonkey

options:
  bundleIdPrefix: dev.copt
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: L7U86T3YRV
    CODE_SIGN_STYLE: Automatic

targets:
  GalaxyMonkey:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: GalaxyMonkey
        excludes:
          - "Info.plist"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.copt.GalaxyMonkey
        PRODUCT_NAME: GalaxyMonkey
        INFOPLIST_FILE: GalaxyMonkey/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1"
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  GalaxyMonkeyUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: GalaxyMonkeyUITests
    dependencies:
      - target: GalaxyMonkey
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.copt.GalaxyMonkeyUITests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: GalaxyMonkey

schemes:
  GalaxyMonkey:
    build:
      targets:
        GalaxyMonkey: all
        GalaxyMonkeyUITests: [test]
    test:
      targets:
        - GalaxyMonkeyUITests
      gatherCoverageData: false
